Q5) Create a 2-D Array of three rows and four columns, named ucs420_<your_name>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>.

In [ ]:
import numpy as np

# Create the 2-D array ucs420_<your_name> with 3 rows and 4 columns
ucs420_your_name = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])

# Compute mean, median, max, min, and unique elements
mean_value = np.mean(ucs420_your_name)
median_value = np.median(ucs420_your_name)
max_value = np.max(ucs420_your_name)
min_value = np.min(ucs420_your_name)
unique_elements = np.unique(ucs420_your_name)

# Print the computed statistics
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements)

# Reshape the array to 4 rows and 3 columns
reshaped_ucs420_your_name = ucs420_your_name.reshape(4, 3)
print("\nReshaped array (4 rows and 3 columns):")
print(reshaped_ucs420_your_name)

# Resize the array to 2 rows and 3 columns using np.resize()
resized_ucs420_your_name = np.resize(ucs420_your_name, (2, 3))
print("\nResized array (2 rows and 3 columns):")
print(resized_ucs420_your_name)



Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 rows and 3 columns):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 rows and 3 columns):
[[10 20 30]
 [40 50 60]]
