Q1) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), Find

i. Sum of all elements

In [1]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original matrix: \n", gfg)
print("\nSum of all elements: ", np.sum(gfg))

Original matrix: 
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements:  45


ii. Sum of all elements row-wise

In [2]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original matrix: \n", gfg)
print("\nSum of all elements row-wise: \n", np.sum(gfg, axis=1))

Original matrix: 
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements row-wise: 
 [[14]
 [16]
 [15]]


iii. Sum of all elements column-wise

In [3]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original matrix: \n", gfg)
print("\nSum of all elements column-wise: ", np.sum(gfg, axis=0))

Original matrix: 
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements column-wise:  [[20  9 16]]
