Q3) You are given a weekly sales dataset and need to perform various operations
using NumPy broadcasting.

a) Generate your unique sales dataset:

*   Take the sum of the ASCII values of the initials of your first and last name. Call this value X. (If your initials are A B → ASCII sum = 65+66=131 → sales = [131, 181, 231, 281, 331].)
*   Create a NumPy array sales with values [X, X+50, X+100, X+150,
X+200].



In [1]:
import numpy as np

# Sum of ASCII values (X)
X = 75 + 69

# Create sales array
sales = np.array([X, X+50, X+100, X+150, X+200])
print("Sales dataset:", sales)

Sales dataset: [144 194 244 294 344]


b) Compute your personalized tax rate as ((X % 5) + 5) / 100.

*   Use broadcasting to apply this tax rate to each sales value.



In [2]:
tax_rate = ((X % 5)+5)/100
print("Tax rate: ", tax_rate)
print("Tax added on each sale: ", sales*tax_rate)
sales_with_tax = sales *(1+tax_rate)
print("Sales with tax: ", sales_with_tax)

Tax rate:  0.09
Tax added on each sale:  [12.96 17.46 21.96 26.46 30.96]
Sales with tax:  [156.96 211.46 265.96 320.46 374.96]


c) Adjust sales based on discount:


*   If sales < X+100, apply a 5% discount.
*   If sales >= X+100, apply a 10% discount.


In [3]:
discounted_sales = np.where(sales < X + 100, sales * 0.95, sales * 0.90)
print("Discounted sales:", discounted_sales)

Discounted sales: [136.8 184.3 219.6 264.6 309.6]


d) Expand sales data for multiple weeks:

*   Create a 3×5 matrix representing three weeks of sales by stacking
sales three times using broadcasting.
*  Increase sales by 2% per week using element-wise broadcasting.



In [4]:
weeks_sales = np.tile(sales, (3,1))
print("Sales for three weeks:\n", weeks_sales)

#increase sales by 2% per week
weeks_sales = weeks_sales * 1.02 ** np.arange(3).reshape(3, 1)
print("\nSales after 2% increase per week:\n", weeks_sales)

Sales for three weeks:
 [[144 194 244 294 344]
 [144 194 244 294 344]
 [144 194 244 294 344]]

Sales after 2% increase per week:
 [[144.     194.     244.     294.     344.    ]
 [146.88   197.88   248.88   299.88   350.88  ]
 [149.8176 201.8376 253.8576 305.8776 357.8976]]
